name: Project CI Automation

# यह ऑटोमेशन तब एक्टिव होगा जब भी कोई main ब्रांच के लिए Pull Request (PR) बनाएगा
on:
  pull_request:
    branches: [ main ]

jobs:
  code-quality-and-test:
    runs-on: ubuntu-latest # गिटहब हमें एक फ्री लिनक्स सर्वर देगा इसे रन करने के लिए
    steps:
      # 1. यह स्टेप गिटहब के सर्वर पर आपका कोड डाउनलोड करता है
      - name: Checkout Code
        uses: actions/checkout@v4.2.2 

      # 2. यह स्टेप एक नकली कोड स्कैन (Linting) चलाएगा
      - name: Run Code Linter Scan
        run: |
          echo "Scanning code syntax and formatting..."
          echo "Formatting look perfect! No errors found."

      # 3. यह स्टेप प्रोजेक्ट के टेस्ट रन करेगा
      - name: Run Project Unit Tests
        run: |
          echo "Executing project test suites..."
          echo "All 5 core tests passed successfully!"
	  echo "Oh no! A critical bug was found in the code!"
      # यह कमांड आपके टेस्ट को जबरदस्ती फेल कर देगा |
          exit 1 
